export const metadata = {
    title: 'Terms of Service | MedAssist',
    description: 'MedAssist terms of service and user agreements.'
};

export default function TermsPage() {
    return (
        <div style={{
            maxWidth: 680,
            margin: '0 auto',
            padding: '48px 24px',
            background: '#FDFDFB',
            minHeight: '100dvh'
        }}>
            <h1 style={{
                fontFamily: 'Instrument Serif',
                fontSize: 36,
                color: '#0F172A',
                margin: '0 0 8px 0'
            }}>
                Terms of Service
            </h1>
            <p style={{ color: '#94A3B8', fontSize: 13, margin: '0 0 40px 0' }}>
                Last updated: February 2026
            </p>

            {[
                {
                    title: 'What MedAssist is',
                    content: 'MedAssist is an educational tool that helps you understand your lab results in plain English and prepare questions for doctor visits. It is not a medical device, does not provide medical diagnosis, and is not a substitute for professional medical advice.'
                },
                {
                    title: 'What we store',
                    content: 'We store your email address, the basic profile information you provide during onboarding, and the biomarker values extracted from your lab reports. We do not store your original PDF files.'
                },
                {
                    title: 'Who can see your data',
                    content: 'Only you can see your health data. Your account credentials control access to your records, and we do not share or sell your personal health information.'
                },
                {
                    title: 'AI-generated content',
                    content: 'The explanations, interpretations, appointment summaries, and doctor questions provided by MedAssist are generated by AI and are for educational purposes only. They may contain errors. Always consult a qualified physician before making any health decisions.'
                },
                {
                    title: 'Deleting your data',
                    content: 'You can delete your account and all associated data at any time from Settings > Delete Account. This action is permanent and cannot be undone.'
                },
                {
                    title: 'Changes to these terms',
                    content: 'We may update these terms as the product evolves. We will notify users of significant changes via email.'
                }
            ].map(section => (
                <div key={section.title} style={{ marginBottom: 32 }}>
                    <h2 style={{
                        fontSize: 18,
                        fontWeight: 600,
                        color: '#0F172A',
                        margin: '0 0 8px 0'
                    }}>
                        {section.title}
                    </h2>
                    <p style={{
                        fontSize: 15,
                        color: '#475569',
                        lineHeight: 1.7,
                        margin: 0
                    }}>
                        {section.content}
                    </p>
                </div>
            ))}

            <div style={{
                marginTop: 48,
                paddingTop: 24,
                borderTop: '1px solid #EBEAE4'
            }}>
                <p style={{ fontSize: 13, color: '#94A3B8' }}>
                    Questions? Contact us at support@medassist.app
                </p>
            </div>
        </div>
    )
}
