'use client'

import { Activity } from 'lucide-react'

interface LongitudinalInsightsSectionProps {
    insights: string[];
}

export function LongitudinalInsightsSection({ insights }: LongitudinalInsightsSectionProps) {
    if (insights.length === 0) return null;

    return (
        <div className="bg-[#FBFCFE] border border-[#E0E7FF] rounded-[18px] p-6 mb-6 shadow-sm">
            <div className="flex items-center gap-2 mb-4">
                <Activity className="w-5 h-5 text-indigo-500" />
                <h3 className="text-[18px] font-bold text-[#1C1917]">Trend Context for Your Visit</h3>
                <span className="text-[11px] font-bold text-indigo-400 uppercase tracking-widest ml-auto">Beta</span>
            </div>

            <div className="grid grid-cols-1 gap-4">
                {insights.map((insight, idx) => (
                    <div
                        key={idx}
                        className="flex gap-3 items-start bg-white p-4 rounded-lg border border-[#EEF2FF] min-w-0"
                    >
                        <div className="mt-1 w-2 h-2 rounded-full bg-indigo-500 shrink-0" />
                        <p className="text-[14px] text-[#475569] leading-relaxed break-words min-w-0">{insight}</p>
                    </div>
                ))}
            </div>

            <p className="mt-4 text-[11px] text-[#94A3B8] italic">
                * Generated by comparing your latest results with up to 10 previous reports so you can discuss changes, not isolated numbers.
            </p>
        </div>
    );
}
